version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: 8rujm2.w08bg8wzszc1kngf
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBbHUyTjRENlFQU2RIZlczeUpCQTJ4VEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdOREE0TVRZek5qRTNXaGNOTXpZd05EQTFNVFl6TmpFM1dqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQU9sRS9NdjlXemtnTi9uMG1EOEVJV3dyY0E0Rm1ib1FZbzI4CkFqcy9IS2FKbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkZhTFpEcC9sUFV3bVJMYQpLTENPdkV0RHMxZFZNQVVHQXl0bGNBTkJBQjluRWhrL3pnQmNQY2V3RVFxb1lJNnA5SWtRN0ZPbXI3WVYvK0x2CnFhY2dqUU9KdTRMMHJuanNPWDNnQ0N3b0lXVnlTQXRMNWZ5YUpNbVNIUGFuVWdVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJQU9mcWp3RWpobWF0MEs5QlNWMU1DM29OM01yZWx0VWxmUHQ0QmdmKzRiSQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.35.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    kernel:
        modules:
            - name: host1x
            - name: host1x_fence
            - name: nvhost_ctrl_shim
            - name: nvmap
            - name: mc_utils
            - name: nvgpu
            - name: governor_pod_scaling
    install:
        disk: /dev/nvme0n1
        image: ghcr.io/schwankner/custom-installer:v1.13.0-6.18.24-nvgpu5.10.7
        wipe: false
    features:
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: qrxoa6dBWtiB9YJbWgR98MlmEEH96zea1X51BeIVfsw=
    secret: QjQWpFIyFlN4p9rreagtAZkg7fXavPTEXmoPhZHLHEY=
    controlPlane:
        endpoint: https://10.0.10.38:6443
    clusterName: jetson-cluster
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: tzu5wb.4bqmopj6nlvdb3az
    secretboxEncryptionSecret: NZQ/tDGUT3C7NdIcLbdyYX+YnH3Ze2QAupcXEnFyrDM=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUl1Um84NnlYc2gzWFJPWnhwR25PWTR3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakEwTURneE5qTTJNVGRhRncwek5qQTBNRFV4TmpNMgpNVGRhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVF5TXFwVktUd1lsWGVaSFZiUlNNUHhuMjZ2ejM4ZG5iVVlRd1E3N0ZoMTkzdFprVXFadE5JM09scmMKYWlpNDVCZ2tJZjdWeVFpTjFZcmdaR1hHZXV1dG8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGUFBiVGE0cXhCeXI1TDBlSlZ3cnV5RnBtZytyTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDaDVVZ1AKcVJ6cERqcVh0ZHRnUWRnMng3MEJtdDU2Ykx5TS9rK05aMDJJSWdJZ0dCeTRSMVV3YjZiLzZPNjh5RlczV0hSbQpGbHNDNjJCN1NSanVxc09ENUM0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdqRWVNbWNkVWNLcWRlL2tjNVluaXMyWmE4WkZHbHVoTUdQU1RzUllYWjhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTWpLcVZTazhHSlYzbVIxVzBVakQ4Wjl1cjg5L0haMjFHRU1FTyt4WWRmZDdXWkZLbWJUUwpOenBhM0dvb3VPUVlKQ0grMWNrSWpkV0s0R1JseG5ycnJRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYekNDQVFXZ0F3SUJBZ0lRSlRGQnlRc1NnTXY4RC9hU2NUdmE5akFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMk1EUXdPREUyTXpZeE4xb1hEVE0yTURRd05URTJNell4TjFvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCT3IrYW54ajNoRXhzY2RjalJHczZhZGwvZlFQNVZnRWhSRFRVSFZubytjNDBpVFpiUUlyCmlBd0tVd01zNHRxT0o0WTlyb1hheDBPY0NQUEdVaGZ0UGxtallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVV4QVQ0dGFPWDdxRG9jcGNqc1NPRElOWWJWY293Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloCkFOZW16TEdQSDZ3QXp0TFJyNS9ldmFXbVNTVExTY3loNzdkdFRwNHdzcGdnQWlCcjFaQkQwbk5vRHlHZFZhK0oKV05pSXVRK1ROS0x6ek5uZjBOTmYzdVhiL1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxIcWhLV2RKeW5iR2lBUW02VXc3ZkNZd3lWVndOUWlZOTMxaHBLVEhkYTVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNnY1cWZHUGVFVEd4eDF5TkVhenBwMlg5OUEvbFdBU0ZFTk5RZFdlajV6alNKTmx0QWl1SQpEQXBUQXl6aTJvNG5oajJ1aGRySFE1d0k4OFpTRiswK1dRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBMUNhK3MxWUltUVdITXFPY3RuUDU4Vmk5MmlKOFVJa3U1T2NsSzBLVWttcERrRmJOCll0eXZJMnJmOXUrRWdXcUpMMmtlZXRVckFyVWhIZzJMQ3ZtUzNIRzVVOUZQVUhFZjFma1dJclpjOUc2SncrWkoKaUJ5UHBRSWRLdWx5aERPNHRnWUJYOVNRWHo5V3kvc2Z0UDdKcHJqeWFMYk0wYmRKTE4yZSs2bFk3OGRhUTFwZQpsUVluVzRFKzdmWU04M1F2enVKL1MxcUdOSitoT25YV3JBa2xIamRvMHhmeWlERElnZkV5YUpNS2d3WTlGWm1DCnZTdGhRbzQ4VjY3aWRZdVJEakt4ZUx2ZlNPZ2FPZVBlUzZKTC9iUE1VSFdabncvajhRejI1Z1FPa0VTZmI5QmoKamUycTcvZVlZbTdINUpPUjlQck84RHM3R2NJNkFTQmt4SnBCNklWVjVjWTFsRXRrV1Bmczh1dGpaSG1zeFNYVQpaN09KeXpsdkNDa2R5ZVJwelNPZmNGaEx5a1NBRTJHTHlwM0lSOUZDUldKVGRyWWhPQ0Jxclk3Z3FLVEFYNG9XCjlHZDU1eUluNjBJKzNQYU4vWFc3OE9DM1dud2ZjcEVYUzAvdW9GNFdwVHcyQzRZVFBOYjdaRWo4WjdHbitvdVUKMHB1UjVtMUhxQnhnb240MnFtWXBpN0RFS1Z6NW5lMWs5Zzh6aUNvMW1Id0xSazFpQkRHOG5OaGQvVnFsa2VSawpML1NzQ1FDOHlTNjl1Q1BNbVlXOFVRbFlLVnczYlZTQzB4TG1BeVNFa0dxSEdGSWxZRFMzSUtuYjBjVkJhM2xICllTYm9HV1BibXFiRXB1NlVzRVU2TExBNTQrTmkvdTNjUHpFSGc4a0JmOWtISm5BcVREYjFOM0FJdXM4Q0F3RUEKQVFLQ0FnQUZEc0R4a01sdEVnTmNRd0JHSG5yRTNFTWV1YUcrSlNoU3owMGRkM0ZESmR0alFqY2Q0cUVlUUZnKwpYelIvR2FWNjFhTzJ3L0VpeVFEM2Y1b1VTeUhMUDNBTUtuOHdRVjUxS0c3MHZReXlhZHI2S21FM0tIdDF1bkZBCkIvT2kzMXJ3OHJxZ1JpZmRIRFRwNTRpazBvVTlqZ3YxRlcxVGhWcGtaT05BRnFmOCtkdkRRUDFHM2VzNmI1M1MKTnoyR0c2enBCaHIrN3g5MjNZdjdJZlc4YlpmLzhLVFh6TFNWWi9zWEhWY0FzT253MnhnUW9ZZEJPZC9CVTBpLwptd0M2QStQWWkvV2JVTE9XdGwyRUovSFkwTlE3R2x5WjQ2MnRmM2tZK2lDSHlaUXo2ektWUFhETk9TcHVuVlY1CnJicEZKNWZJZitIa2RmS1JTUzJObUkyUTV1MTJ6MW5PS25QZENuUWttZDg0aUdXblliQVdGdGd3OEVIN2lSOHAKYlJGQ3FoMVR5eU5ncWJWNVVubUZaOHF3UjNzcEhOMU1KeXVSbWg5bHErcmpBbGhQSDdPbjFsbmVYOVNEUHlwLwpyVmxjNmdxQURvOE5JbHRya2FuL0dHVlo0SzRuZ3dCdTZoYVJrVlhZSGhaanRMK0dIdTh4VlUzSkRYL3lPZjBCCkJxbUN0YjFJVHZ3OE0wdis3cGpDYithaTVkYzRvSWNINmYrRmR5U2RMdjhFb2pmN2xSUmVwRCtUK2U3bEdMM3kKQmFNUGYyL3NKeGRRT2E0Nk1nSjVYeHR6TFk3eXZ3NnlPQzhXVnZlWDRoMjZTQjZmRUZOSDFjRjF4b3k2and3TQpVak10VGZ0TXpiNGNUUGgvcTRFUFpOOStaZWJNSXlyckJIc2xPb2c3UHQ3WlZiaGFFUUtDQVFFQThzdG44QUc2CnZweEc3NUkvclBFekpTTmppRGZ4UklKVUVjNThvcFBtb0VBS1c0TmZBd3lOYkVFWVVqL2FLZkpjSTR5bGxBcTIKeXBORktBdUk1ZUJRdW44ZE5hU0w0TWZMMnJ0YVlzTG91SkhZRFhXYkpBN0UyZ0c4ak1SeE8wL1IzNGNablphLwozYjBOdWJ0N2Fwa0NVZHdjTllHVHhOWmFRV3EyUFZBSU1SeG93akZSVytDR3ppQzcySW8xYzc2UFIvZDR5ODVRCmhQZjVMbCtuMWswdXBFRVQrT3RhclhwMXJnQVEvcEM1alBFaWhVbG83UktvVkJEbGtjWHgyMzFNMDdaOW5UUUEKYks0YlBMSEsvUGFUUTFpclJiQ20wcUx6QUlkbVcrVThDRDNwNUxzbXl6OHNmcGU4ZWg1UEtrdE5JZDJWbjB6MQo1Lzd2LzZpS2Jhd1hpUUtDQVFFQTM3Q3NNOUgvNmp3K3hrQVFpZE5FYURrYTUrcVJRZEdrY3ZrWmFMc3B0aTRwCmdQSFFXRnp0ZVJ5SFJCRWF6OXh0aFZ3ZXpZS3dtQVBuNmxQWmM2OUY4OXVFK3BERUZLS25jQk51VE1lU29pNlMKUWlydkJlS2M1RmgvYWtFMlBHU3lKY2wvOEVGQUdsS2t5K1ZieFAzSFc3bHNQVEFqY1A1RWdNbjErTkN0WVdpcgpzbm5hMkQzQkExVmtnQmNJVWs4WW5JWGVlNjhHcWduRlFEVVp6NCtzbUlkbWRwd0dSanROQnZGQS9DSUUvN0VMClAzU2VrU21iUW4rS1ZtWFhGTnAydlhlZGNNays2TkVpb2ZsWW1XenlXYVZlWTNMQjF1M0pVYVdhaUluRUxGU3UKRlAvbmprOHI5SUxrTmRZN1JUNklWU1JqaGl0TGkzSllOMmo1MmREUmx3S0NBUUJwZFRSV0tVb2wxTmR5NDhGSQpxeE9lQS9zTmhjOEVCTi9qUkI4YXRzY3J2K1UvenBZTVN2MTZrZU93aGcrS3ZMeU1yR0NYSnZneWtUa3VwYVAyCnhUSUxiMzhPZDhSU0JEWmxjWTlXNm5ZUEJUb2t6bnB1ZFFQSDlZMGlUNGtuVEFwSzN2R2ZZNFUvR1FqSExjbnoKaVRaYXZCSjhveVcrRDZUd1dSdURFaW9jdXN3OTNSSUxxRUNsYzg1anhkUmx5OVdNV3M5Ykp1Z09lVzhBVjRnZApLelVoSHlzL3FXcWZnMXR1RXBWUEhTbWJNSG5nRHZ6R1RKNVV0V29ob1NybVBVeUxnTzZhdzZXVGp5UkJmckErCnBCTmU0enF4Y0lObFptWEtTd1dJME03OGZYZ0VZODM3NWhxN2VjamgraHhFc0tSMkd6c01FRytYTDBLcmQxZDUKUDVDUkFvSUJBUUNlTU9nbklZelZEdFBxQ2Vab1FlTXZ2YXE4ZGhOUnM3dVRuM3dMcDhqZzBKYURYUDlWYmlwMgpxdWt5QnRLcVN4MmM0VC9iWUdBWXNUSnljZWZuT3YzQ2JlMEY4aGpvNnZwMGRSbGM3UXBTN1pKN2ZyZFl0eUR6CkQyN1VLdGY3TDg4WWovNk5YdWZCZGM2YmIxRk41NWJ6MUJhcTB2OU5hbFB4ckdIcUcxRnlBTDdqMGU4bFc4N0MKMThIaUgrZS9wYlluQXprS3lRVnlmTVJsR3VoczlCTkFMd2tVT2xUcG1BaHFMM1VnbWNKbFBNUlNsTnVLbHh6NAprdysyK0FCNSsrRmJMbHRHSnR2NWMrVUZIVHcrREdEN2FzcHNrL3huVGZSQWJGZnoxVkhKYy8xRVZwRmYvN2Q3CkRKSHRUTnJQcG1CdHJmVkFMaUFYdHI2U09RZnd0UTl6QW9JQkFRRGszVHFYYmVjd1h2OEQvakVUZC9Cbk13ek4KWUxKSHZHMVpqRHdKUUxZT3pCOGw0Smc5SFhIMG54SHN3TWlBVjdpaWR2dlIyeEF6RmdGRHBhUlpTQW12YW5kVQo3eEJtTmluUmhaVVhlUE5JbDNRUUhVVGc1VWZwTEpIaTBudzdETnpNbWxMYTJidTFueTExMXNFcWk4ekJnQXdLCmo2em9PeDVnL1pIRXMvcUg1cXoyY1pRZVMzYzhNb09IcGdOZnF1bUVoK2drWXZJNThXdVdXVjcyTlZyWFdTazkKc3BqcmE5TjJtREd0L3p0MHdQSHpiU3k4c0JQM1pNaXF3aFFFZWZyZEVsR0ZudlFBZ0IvOEFGRWU3SERBQUxsMgo5blVPbkRoaFlqeDFYMnNmTEtWdzBuc2JSdkxCMkd2YTV3VVhDd2R6YWdmS0N3czgrRlFYUVdmUkdYNXkKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.35.2
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.35.2
    proxy:
        image: registry.k8s.io/kube-proxy:v1.35.2
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.35.2
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmekNDQVNTZ0F3SUJBZ0lSQVBneUcvUFltemhzVzNUUkxidWlWLzh3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TmpBME1EZ3hOak0yTVRkYUZ3MHpOakEwTURVeE5qTTJNVGRhTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTVDUvY1E5NGZ2CnllNHFMY2k3K2xpRWJSU1pPdFBQZDUvQjdEUmFZSWpVcXNDbXNSRjBYcnZPcGtJbEE5cWZGNWg2Yi9Eend6b3QKR0F4V2piVzZ1TzQwbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRlBTcHM4djFldCthCmxuSmRsQUxnd1FvYkNlMHRNQW9HQ0NxR1NNNDlCQU1DQTBrQU1FWUNJUUM1RUczWlJaQzNKSnRaZ0dmaXVxMzIKNW45TEVlQWFvQkpaOVp3cUZ2L0ZHZ0loQVBRVVlrTGRBUFozVWQ1YzFSRjhPSHVpZ2RYdVdJeTRXQzRPa0VCZgp1U25VCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9MWWVSK2sxbmV4YzFrNU9Wd1FGcndkNmcvNnRwdFVhS20wbXhjQisvYW1vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFaytmM0VQZUg3OG51S2kzSXUvcFloRzBVbVRyVHozZWZ3ZXcwV21DSTFLckFwckVSZEY2Nwp6cVpDSlFQYW54ZVllbS93ODhNNkxSZ01WbzIxdXJqdU5BPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
